### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xiajunwen1007** [njpipeorgan/wolfram-language-notebook#1]
无法使用类型为“wolfram-language-notebook”的笔记本编辑器打开资源，请检查是否已安装或启用了正确的扩展。

终端中出现如下错误

```
[2021-11-30 21:10:31.916] [renderer1] [info] Starting extension host with pid 42715.
[2021-11-30 21:10:31.917] [renderer1] [info] [LocalProcessExtensionHost]: IExtensionHostStarter.start() took 12 ms.
[2021-11-30 21:10:32.089] [renderer1] [error] [Extension Host] (node:42715) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
```

**Comment by njpipeorgan** [comment]
你正在使用的vscode的版本是多少？

**Comment by xiajunwen1007** [comment]
我使用的是m1的电脑，运行的是arm架构的vscode
版本: 1.62.3
提交: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
日期: 2021-11-17T08:14:33.711Z (1 周前)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0

**Comment by xiajunwen1007** [comment]
好像这个才是扩展启动不了的原因
[2021-12-01 01:01:53.024] [exthost] [error] Activating extension njpipeorgan.wolfram-language-notebook failed due to an error:
[2021-12-01 01:01:53.024] [exthost] [error] Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=89 uv=1 armv=8 libc=glibc node=14.16.0 electron=13.5.2
    loaded from: /Users/xiajunwen/.vscode/extensions/njpipeorgan.wolfram-language-notebook-0.0.2/node_modules/zeromq

**Comment by xiajunwen1007** [comment]
安装了intel版本的vscode后原本的错误消失了，目前有这个错误
Kernel "wolframscript" has been disconnected.

**Comment by xiajunwen1007** [comment]
直接在终端输入 wolframscript 是可以启动的

**Comment by njpipeorgan** [comment]
我现在没有macOS可以测试，所以也不太清楚是为什么。如果只有这一个错误的话，你可以试试在启动kernel之前从Command Palette中打开**Webview: Open Webview Developer Tools**，启动kernel过程中的消息会在里面显示。可以看看这里面能不能找到一些线索。

我这里在能正常启动的情况下会显示：
```
[Extension Host] WLNotebookController(), this.extensionPath = c:\Users\...\.vscode\extensions\njpipeorgan.wolfram-language-notebook-0.0.2
webviewCommands.ts:28 Using standard dev tools to debug iframe based webview
[Extension Host] remote = false, port = 62614
[Extension Host] launchCommand = wolframscript
[Extension Host] launchArguments =  -code,ToExpression["zmqPort=62614;"<>Uncompress["1:eJzFXI1T20iyvz9FGSjKULJjJ7V3rwD5mRByYRdIwM5t1So6EPIE65AlryQHvMb7t7/u+ZBmRpLxJrv3qHzYmpmenu6e7l/3jHhxm1wN26d/+1trz9rf/+gH9/4d3d+39nY/d3uv8C9rGNIgD5O4a
[Extension Host] Received the following data from kernel:
[Extension Host] <INITIALIZATION STARTS>
[Extension Host] Received the following data from kernel:
[Extension Host] Kernel connected; $preemptive=LinkObject[cj68v_shm, 213, 4], $processID=71192
[Extension Host] Received the following data from kernel:
[Extension Host] [address tcp://127.0.0.1:62614]
[Extension Host] Received the following data from kernel:
[Extension Host] <INITIALIZATION ENDS>
[Extension Host] Received the following test message from kernel:
[Extension Host] {"type":"test","text":"869928873","version":"12.3.1 for Microsoft Windows (64-bit) (June 24, 2021)"}
```

**Comment by xiajunwen1007** [comment]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/49160447/144145659-75608c0a-fab9-44e3-87a2-8ccaf99a6fc0.png">

**Comment by njpipeorgan** [comment]
我在Catalina的虚拟机上试了一下，没能复现出你遇到的情况。一个最接近的情况是我把创建subkernel的命令人为地改成一个不存在的文件，这样就能得到LinkOpen::linke的错误，不过在正常情况下应该是不会发生的。
我更新了一个版本，把所有的log都放在Output窗口了，在连接失败之后你应该可以在Output看到与之前类似的记录。其中有一行应该会是“Using the following command to launch subkernel: ...”，你可以看一下这个command在你的环境下是什么。

**Comment by xiajunwen1007** [comment]
Using the following command to launch subkernel: /Applications/Wolfram Engine.app/Contents/Resources/Wolfram Player.app/Contents/MacOS/WolframKernel -wstp

**Comment by xiajunwen1007** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/49160447/144246641-a6b37371-08bb-41e9-8024-6d25d07cc9d9.png">
这个文件应该是存在的

**Comment by xiajunwen1007** [comment]
[Wed, 01 Dec 2021 13:51:29 GMT] kernelIsRemote = false, kernelPort = 58181
[Wed, 01 Dec 2021 13:51:31 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 13:51:31 GMT] <INITIALIZATION STARTS>
[Wed, 01 Dec 2021 13:51:31 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 13:51:31 GMT] $CommandLine={/Applications/Wolfram Engine.app/Contents/Resources/Wolfram Player.app/Contents/MacOS/WolframKernel, -runfirst, Unprotect[$EvaluationEnvironment];$EvaluationEnvironment="Script";Protect[$EvaluationEn
[Wed, 01 Dec 2021 13:51:31 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 13:51:31 GMT] $ScriptCommandLine={wolframscript, -code, ToExpression["zmqPort=58181;"<>Uncompress["1:eJzFPP1T47iS70/xCIoKlJNJZmvfXQHOhWGYG94CAyTztmo9fmAcDfHh2FnbGciG7J99P1+3PmxJtkN2ZvcdNR+J1Gq1ulv9JYlXd8n18H9P//a31p61v3/pBw/+Pd3ft/Z2
[Wed, 01 Dec 2021 13:51:31 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 13:51:31 GMT] Using the following command to launch subkernel: /Applications/Wolfram Engine.app/Contents/Resources/Wolfram Player.app/Contents/MacOS/WolframKernel -wstp
[Wed, 01 Dec 2021 13:51:31 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 13:51:31 GMT] Failed to launch computation kernel; $kernel=$Failed<ERROR> Failed to launch computation kernel.
[Wed, 01 Dec 2021 13:51:31 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 13:51:31 GMT] 
LinkOpen::linke: Could not find MathLink executable.

[Wed, 01 Dec 2021 13:51:31 GMT] Killing kernel
[Wed, 01 Dec 2021 13:51:31 GMT] Process exited with code 0 and signal null.

这是完整的输出

**Comment by xiajunwen1007** [comment]
我在命令行中输入 `$ScriptCommandLine` 会没有返回值，不知道会不会有影响
<img width="682" alt="image" src="https://user-images.githubusercontent.com/49160447/144247382-584e5973-2708-457b-823d-9f3c521b3cf6.png">

**Comment by xiajunwen1007** [comment]
会不会是因为/Applications/Wolfram Engine.app/Contents/Resources/Wolfram Player.app/Contents/MacOS/WolframKernel中间含有空格

**Comment by xiajunwen1007** [comment]
/Applications/Wolfram\ Engine.app/Contents/Resources/Wolfram\ Player.app/Contents/MacOS/WolframKernel可能需要改成这样？

**Comment by njpipeorgan** [comment]
确实就是这个问题，我把连接subkernel的命令加上了escape，你更新一下试试看

**Comment by xiajunwen1007** [comment]
The kernel has stopped due to the following error: The first packet is not a InputNamePacket; packet=$Failed
还是又问题

**Comment by xiajunwen1007** [comment]
[Wed, 01 Dec 2021 23:48:00 GMT] kernelIsRemote = false, kernelPort = 50063
[Wed, 01 Dec 2021 23:48:00 GMT] launchCommand = wolframscript
[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments = -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM9QsmOS2rv3APlMCHnhli8BO5eqVXQgrAnWIUteSQ54jfO3X/d8kWZGkvElu/eoSrA1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe
[Wed, 01 Dec 2021 23:48:01 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 23:48:01 GMT] <INITIALIZATION STARTS>
[Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 23:48:02 GMT] $CommandLine={/Applications/Wolfram Engine.app/Contents/Resources/Wolfram Player.app/Contents/MacOS/WolframKernel, -runfirst, Unprotect[$EvaluationEnvironment];$EvaluationEnvironment="Script";Protect[$EvaluationEn
[Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 23:48:02 GMT] $ScriptCommandLine={wolframscript, -code, ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM9QsmOS2rv3APlMCHnhli8BO5eqVXQgrAnWIUteSQ54jfO3X/d8kWZGkvElu/eoSrA1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn
[Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 23:48:02 GMT] Using the following command to launch subkernel: /Applications/Wolfram\ Engine.app/Contents/Resources/Wolfram\ Player.app/Contents/MacOS/WolframKernel -wstp
[Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel:
[Wed, 01 Dec 2021 23:48:02 GMT] 
LinkObject::linkd: Unable to communicate with closed link LinkObject[/Applications/Wolfram\ Engine.app/Contents/Resources/Wolfram\ Player.app/Contents/MacOS/WolframKernel -wstp, 185, 2].

[Wed, 01 Dec 2021 23:48:02 GMT] Killing kernel process, pid = 8428
[Wed, 01 Dec 2021 23:48:02 GMT] Process exited with code 0 and signal null.

**Comment by xiajunwen1007** [comment]
这里有个类似的问题
https://mathematica.stackexchange.com/questions/5244/how-to-protect-existing-mathlink-connection-from-disconnecting

**Comment by njpipeorgan** [comment]
这个我不清楚是什么原因，不过应该是在[这里附近](https://github.com/njpipeorgan/wolfram-language-notebook/blob/8a457cb8359a01f74dae1d6ba6217053ec424c4b/resources/init.wl#L110)出的问题。我现在只有Catalina和12.2（是正常的），没法和你用一样的环境。

你可以在shell的wolframscript里运行这几行代码
```Mathematica
$kernel=LinkLaunch["/Applications/Wolfram\\ Engine.app/Contents/Resources/Wolfram\\ Player.app/Contents/MacOS/WolframKernel -wstp"];
While[!(LinkReadyQ[$kernel]),Pause[0.1];];
LinkRead[$kernel]
```
看看能不能复现这个`LinkObject::linkd`，理论上正常的话应该会得到`InputNamePacket["In[1]:= "]`。

**Comment by xiajunwen1007** [comment]
In[1]:= [Wed, 01 Dec 2021 23:48:00 GMT] kernelIsRemote = false, kernelPort = 500
63                                                                              

Syntax::sntxb: Expression cannot begin with 
    "[Wed, 01 Dec 2021 23:48:00 GMT] kernelIsRemote = false, kernelPort = 50063"

    .

In[2]:= [Wed, 01 Dec 2021 23:48:00 GMT] launchCommand = wolframscript           

Syntax::sntxb: Expression cannot begin with 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchCommand = wolframscript".


In[3]:= [Wed, 01 Dec 2021 23:48:00 GMT] launchArguments = -code,ToExpression["zm
qPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM9QsmOS2rv3APlMCHnhli8BO5eqVXQ
grAnWIUteSQ54jfO3X/d8kWZGkvElu/eoSrA1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urd
n7Wx/7u6+wn+sYUBHe                                                              
[Wed, 01 Dec 2021 23:48:01 GMT] Received the following data from kernel:        
[Wed, 01 Dec 2021 23:48:01 GMT] <INITIALIZATION STARTS>                         
[Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel:        
[Wed, 01 Dec 2021 23:48:02 GMT] $CommandLine={/Applications/Wolfram Engine.app/C
ontents/Resources/Wolfram Player.app/Contents/MacOS/WolframKernel, -runfirst, Un
protect[$EvaluationEnvironment];$EvaluationEnvironment="Script";Protect[$Evaluat
ionEn                                                                           
[Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel:        
[Wed, 01 Dec 2021 23:48:02 GMT] $ScriptCommandLine={wolframscript, -code, ToExpr
ession["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM9QsmOS2rv3APlMCHnhl
i8BO5eqVXQgrAnWIUteSQ54jfO3X/d8kWZGkvElu/eoSrA1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb+
+CP7v07urdn                                                                     
[Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel:        
[Wed, 01 Dec 2021 23:48:02 GMT] Using the following command to launch subkernel:
 /Applications/Wolfram\ Engine.app/Contents/Resources/Wolfram\ Player.app/Conten
ts/MacOS/WolframKernel -wstp                                                    

Syntax::sntxb: Expression cannot begin with 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9Qs<<61>>A1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe"

    .


Syntax::sntxf: "" cannot be followed by 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9Qs<<61>>A1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe"

    .


Syntax::sntxf: "" cannot be followed by 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9Qs<<61>>A1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe"

    .


Syntax::sntxf: "" cannot be followed by 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9Qs<<61>>A1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe"

    .


Syntax::sntxf: "" cannot be followed by 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9Qs<<61>>A1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe"

    .


Syntax::sntxf: "" cannot be followed by 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9Qs<<61>>A1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe"

    .


Syntax::sntxf: "" cannot be followed by 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9Qs<<61>>A1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe"

    .


Syntax::sntxf: "" cannot be followed by 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9<<64>>1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe".



Syntax::sntxf: "" cannot be followed by 
    "[Wed, 01 Dec 2021 23:48:00 GMT] launchArguments =
       -code,ToExpression["zmqPort=50063;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM
       9<<64>>1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe".


In[12]:= [Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel
:                                                                               

Syntax::sntxb: Expression cannot begin with 
    "[Wed, 01 Dec 2021 23:48:02 GMT] Received the following data from kernel:".


In[13]:= [Wed, 01 Dec 2021 23:48:02 GMT]                                        

Syntax::sntxb: Expression cannot begin with "[Wed, 01 Dec 2021 23:48:02 GMT] ".


In[14]:= LinkObject::linkd: Unable to communicate with closed link LinkObject[/A
pplications/Wolfram\ Engine.app/Contents/Resources/Wolfram\ Player.app/Contents/
MacOS/WolframKernel -wstp, 185, 2].                                             

Syntax::sntxf: "LinkObject::linkd" cannot be followed by 
    ": Unable to communicate with closed link LinkObject[/Applications/Wolfram\
      Engine.app/Contents/Resources/Wolfram\
      Player.app/Contents/MacOS/WolframKernel -wstp, 185, 2].".


In[15]:=                                                                        
In[15]:= [Wed, 01 Dec 2021 23:48:02 GMT] Killing kernel process, pid = 8428     

Syntax::sntxb: Expression cannot begin with 
    "[Wed, 01 Dec 2021 23:48:02 GMT] Killing kernel process, pid = 8428".


In[16]:= [Wed, 01 Dec 2021 23:48:02 GMT] Process exited with code 0 and signal n
ull.

**Comment by xiajunwen1007** [comment]
终于可以了，刚刚重启了一下电脑
