### ISSUE TITLE
Render TeXForm in output

### ISSUE THREAD

**Issue by yfzhao20** [njpipeorgan/wolfram-language-notebook#10]
About this issue of WolframLanguageForJupyter, https://github.com/WolframResearch/WolframLanguageForJupyter/issues/83
![image](https://user-images.githubusercontent.com/80528249/148668399-82023947-80bc-4048-8b50-858cd257a32f.png)

However now `wolfram notebook for vscode` shows 
![image](https://user-images.githubusercontent.com/80528249/148668416-b033a977-217e-46b9-9e1d-f725ff40b7b7.png)

I think it can be more beautiful. Thanks! 😃

**Comment by njpipeorgan** [comment]
Thanks for the feedback! I will add this feature to a future version.

**Comment by njpipeorgan** [comment]
This feature has been implemented in v0.0.8.
