### ISSUE TITLE
add autocomplete when lower case.

### ISSUE THREAD

**Issue by wuyudi** [njpipeorgan/wolfram-language-notebook#12]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

No.

**Describe the solution you'd like**

In Notebook,![](https://pic3.zhimg.com/v2-0a8129adc8af74e2c75baf3bae2012b2_720w.jpg) if this is false, the user can get `Sin` from just typing `sin`

So could there be an option to turn on this behavior?

The default behavior won't change.

**Additional context**

**Comment by njpipeorgan** [comment]
This feature has been added to v0.0.9.
