### ISSUE TITLE
Show multiple lines of definition at one time.

### ISSUE THREAD

**Issue by wuyudi** [njpipeorgan/wolfram-language-notebook#13]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

the definition can't be shown at one glance.

![image](https://user-images.githubusercontent.com/30024051/150635146-ee779289-995d-4070-91b9-0d27ef1fa829.png)

**Describe the solution you'd like**

This may be better?

![image](https://user-images.githubusercontent.com/30024051/150635228-84f24785-f1de-4388-bad2-c2332931c3e1.png)

**Additional context**

**Comment by njpipeorgan** [comment]
Thanks for the feedback. It seems to be a VSCode notebook issue. The two images below show the hover information for python `list` in a normal editor and in a notebook cell. Note that there is no line wrap in the notebook. 
![image](https://user-images.githubusercontent.com/12444637/150669359-f1567ae0-a0ec-47f7-93b8-90d4f62a80cc.png)
![image](https://user-images.githubusercontent.com/12444637/150669348-b2610512-4a6e-49e9-b92b-b01231992e0c.png)

How did you produce the line wrap in your second screenshot?

**Comment by wuyudi** [comment]
I installed both
<https://marketplace.visualstudio.com/items?itemName=WolframResearch.wolfram> and <https://marketplace.visualstudio.com/items?itemName=njpipeorgan.wolfram-language-notebook> , then I open a wl file.

**Comment by njpipeorgan** [comment]
Thanks. So it is a VSCode problem that there is no line wrap in notebooks. The hover panels are shown through a VSCode API. I provide the content in the panel but have no control over how it is rendered.
