### ISSUE TITLE
Association is not correctly rendered

### ISSUE THREAD

**Issue by zhaoruiyang98** [njpipeorgan/wolfram-language-notebook#17]
**Describe the bug**
Association is not correctly rendered

**Expected behavior**
expect `<|x->3, y->4|>`

**Screenshots**
![image](https://user-images.githubusercontent.com/43402887/151388657-81177fba-d99f-4abb-a5f6-2d7a3c2356dc.png)

**Environment (please complete the following information):**
 - Operating system: Windows 10
 - Mathematica/Engine: Wolfram Engine 12.3.1
 - VS Code: 1.63.2
 - Version: v0.0.8

**Comment by njpipeorgan** [comment]
Thanks for the feedback! 

I notice that the appearances of `<|` and `->` were in the form of some special ligatures in the code cell. Did you enable some extensions that involved fonts? 

I would suggest temporarily disabling other extensions and see if the same issue remains. In the meantime, you can evaluate `Hold[<|{(x/y)^2}|>[[x^2]]]` to check the rendering of all parenthesis/brackets.

**Comment by njpipeorgan** [comment]
It has been resolved in v0.0.9
