### ISSUE TITLE
LinksCreate[CreateUUID[]] does not work under macOS

### ISSUE THREAD

**Issue by p-pavel** [njpipeorgan/wolfram-language-notebook#18]
Thank you for the great extension! It looks very promising.

Starting kernel fails with message <pre>The kernel has stopped due to the following error: Failed to create main and preemptive links; $kernel=$Failed</pre>

The probable reason for this is that link cannot be created with `LinkCreate[CreateUUID[]]` under macOS. When I try this in Mathematica notebook I get <img width="298" alt="image" src="https://user-images.githubusercontent.com/415710/152652215-496f7735-a090-4e0c-a5e8-854414c9d1ee.png">

although this works under Linux. 

(see `init.wl` lines 96/97)

Changing these lines to 
```wl
$kernel=LinkCreate[];
$preemptive=LinkCreate[];
```
(and recompressing `init-compressed.txt`) fixes the issue for me (kernel takes care that names are unique)

 - Operating system: macOS Monterey 12.1
 - Mathematica/Engine: 13.0
 - VS Code: 1.64.0
 - Version: 0.0.8

**Comment by BoGGoG** [comment]
I have the same problem. All the same versions except VS Code 1.64.1
