### ISSUE TITLE
Live Print Output

### ISSUE THREAD

**Issue by BoGGoG** [njpipeorgan/wolfram-language-notebook#19]
Thank you for this plugin!

**Is your feature request related to a problem?**

The output only appears at the end of the evaluation.
However, often if one encounters problems, the cell will never fully evaluate.
Stopping the cell leads to no output at all.
This makes debugging really hard.

**Describe the solution you'd like**

Live print output like in Mathematica notebooks.
If possible also `PrintTemporary` output.

**Additional context**

Example code:
```mathematica
Do[
    Print[i]; Pause[1]
    , {i, 1, 5}
]
```

**Comment by njpipeorgan** [comment]
Thanks for the feedback. It should be a bug; I'll investigate this issue and get back to you.

**Comment by njpipeorgan** [comment]
[8c66289](https://github.com/njpipeorgan/wolfram-language-notebook/commit/8c6628978561389ca25eba2c4a334d3b07d6ffe9)
