### ISSUE TITLE
改进html的输出显示

### ISSUE THREAD

**Issue by xiajunwen1007** [njpipeorgan/wolfram-language-notebook#2]
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/49160447/144349472-66c31164-be9b-4a5e-b2a5-bdbe4629b9ec.png">
在输出根号的时候有些难看，不知道能不能改进一下

**Comment by xiajunwen1007** [comment]
感觉像是字体问题，从演示的gif中没有看到有这个问题

**Comment by xiajunwen1007** [comment]
可能可以再添加一个选项，直接显示渲染出来的图片，这样平台兼容性会更好一点。不过可能要注意加上css适配vscode的主题

**Comment by njpipeorgan** [comment]
在这个[新的版本](https://raw.githubusercontent.com/njpipeorgan/wolfram-language-notebook/main/vsix/wolfram-language-notebook-0.0.5.vsix)里：
- 修正了MacOS的字体问题；
- 添加了一个设置，可以全局控制是否将所有的输出都渲染成图片；
- 在深色模式下会给所有的图片添加一个反色反相的滤镜。

你可以试一下在你那边行不行。

**Comment by xiajunwen1007** [comment]
感谢，现在已经好很多了。中括号这还有一点点小问题，看不到中括号下面的横线。
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/49160447/144771821-d56092c9-1a5e-40e9-81c3-8402e41b98c3.png">

**Comment by njpipeorgan** [comment]
这个中括号好像在我这里是正常的，我需要看一下你那边的html，你可以在command palette里运行Open Webview Developer Tools，然后复制一下这个输出的html。
深色模式这个我需要看看这个控制这个是不是可行。

**Comment by xiajunwen1007** [comment]
`<div class="wexpr"><wrow span="33.03 22.97"><w></w><wfrac span="19.58 12.34"><w><w>1</w></w><w><w></w><w><w>12</w></w></w></wfrac><w></w><wsqrt style="margin-top: 0.1em;"><w><w style="height: 0.565em;"><w style="transform:scaleY(0.904)"></w></w></w><w><w style="transform:scaleY(0.840)"></w></w><w><wrow span="13.85 2.67"><w></w><wsqrt style="margin-top: 0.1em;"><w><w style="height: 0.545em;"><w style="transform:scaleY(1.090)"></w></w></w><w><w style="transform:scaleY(1.180)"></w></w><w><w>x</w></w></wsqrt><w>+</w><w>x</w></wrow></w></wsqrt><w></w><wrow span="33.03 22.97"><w></w><wb ch="(" height="6" style="line-height: 14px; height: 56px;"><w><w></w><w style="height:2em;"><w></w><w></w></w><w></w></w></wb><wrow span="32.18 18.07"><w></w><wrow span="12.73 2.67"><w></w><w>-</w><w>3</w></wrow><w>+</w><wrow span="13.85 2.67"><w></w><w>2</w><w></w><wsqrt style="margin-top: 0.1em;"><w><w style="height: 0.545em;"><w style="transform:scaleY(1.090)"></w></w></w><w><w style="transform:scaleY(1.180)"></w></w><w><w>x</w></w></wsqrt></wrow><w>+</w><wrow span="12.73 2.67"><w></w><w>8</w><w></w><w>x</w></wrow><w>+</w><wfrac span="32.18 18.07"><w><wrow span="19.03 8.97"><w></w><w>3</w><w></w><wrow span="19.03 8.97"><w></w><w>ArcSinh</w><wrow span="19.03 8.97"><w></w><wb ch="[" height="2" style="line-height: 14px; height: 28px;"><w><w></w><w style="height:0em;"></w><w></w></w></wb><wsup span="18.46 2.67"><w></w><w>x</w><w style="vertical-align: 7.55125px;"><wrow span="10.91 2.29"><w></w><w>1</w><w>/</w><w>4</w></wrow></w></wsup><wb ch="]" height="2" style="line-height: 14px; height: 28px;"><w><w></w><w style="height:0em;"></w><w></w></w></wb></wrow></wrow></wrow></w><w><w></w><w><wrow span="18.46 2.67"><w></w><wsqrt style="margin-top: 0.1em;"><w><w style="height: 0.565em;"><w style="transform:scaleY(0.904)"></w></w></w><w><w style="transform:scaleY(0.840)"></w></w><w><wrow span="13.85 2.67"><w></w><w>1</w><w>+</w><wsqrt style="margin-top: 0.1em;"><w><w style="height: 0.545em;"><w style="transform:scaleY(1.090)"></w></w></w><w><w style="transform:scaleY(1.180)"></w></w><w><w>x</w></w></wsqrt></wrow></w></wsqrt><w></w><wsup span="18.46 2.67"><w></w><w>x</w><w style="vertical-align: 7.55125px;"><wrow span="10.91 2.29"><w></w><w>1</w><w>/</w><w>4</w></wrow></w></wsup></wrow></w></w></wfrac></wrow><wb ch=")" height="6" style="line-height: 14px; height: 56px;"><w><w></w><w style="height:2em;"><w></w><w></w></w><w></w></w></wb></wrow></wrow></div>`
您看看是这个吗？麻烦了

**Comment by njpipeorgan** [comment]
我调整了分数线两边的宽度，你可以看一下[这个版本](https://raw.githubusercontent.com/njpipeorgan/wolfram-language-notebook/main/vsix/wolfram-language-notebook-0.0.5.vsix)里中括号还会不会和分数线重叠

**Comment by xiajunwen1007** [comment]
目前已经相当完美了，感谢

**Comment by njpipeorgan** [comment]
也谢谢你帮我找到这些问题
