### ISSUE TITLE
`require('mathjax')` in extensions causes error when 'wolfram-language-notebook' is installed

### ISSUE THREAD

**Issue by yfzhao20** [njpipeorgan/wolfram-language-notebook#20]
最近在自己写扩展，发现只要有 `require('mathjax')` ，就会崩，要么报错 `Cannot set property Package of #<Object> which has only a getter.` ，要么 `.wlnb` 打不开。

复现过程：（`wolfram-language-notebook` 已经装好）
1. 使用 `yo code` 或者 `npx yo code` 新建一个 `javascript` 扩展
2. 在扩展文件夹下 `npm install mathjax@3`
3. 在 `extension.js` 中，`hello world` 的函数下加上 `require('mathjax')` ，如图。已经删除各种注释了，这里是最小的示范，只`require` ，不做其他任何事情。
![image](https://user-images.githubusercontent.com/80528249/156001820-2b920331-1a53-4165-a5d2-3e2042abfbf1.png)

4. F5 运行插件，新建/打开一个`.wlnb` 文件，`ctrl+shift+p` 执行命令`hello world` ，然后立即报错：
![image](https://user-images.githubusercontent.com/80528249/156001883-92aeec9b-a0a4-4d20-8b89-e33425aab0ff.png)

5. 如果没有开 `.wlnb` 文件，那么是正常的，可以执行命令：
![image](https://user-images.githubusercontent.com/80528249/156002023-fd058f3e-1f7c-4a91-ba1b-def317786657.png)

6. 但是此时打不开 `.wlnb` 文件：
![image](https://user-images.githubusercontent.com/80528249/156002101-78da050b-c561-4c7f-b2ec-b0957d2a6015.png)

很好奇这个问题。因为上述测试，在 `jupyter notebook` 下是可以跑通的。

这个问题涉及最近写的扩展 [Ultra Math Preview](https://github.com/yfzhao20/vscode-ultra-math-preview). 

**Environment (please complete the following information):**
 - Operating system:win10
 - VS Code: 1.64.0
 - Version: 0.0.9

感谢！

---

一开始不小心按回车发出去了，已修改。

**Comment by njpipeorgan** [comment]
我试了一下，确实有这个情况。产生的异常是对称的（总是后一个激活的扩展会抛出 Cannot set property...）。好像只有mathjax会出现这个问题，所以我怀疑会不会是mathjax的问题。[这里](https://github.com/njpipeorgan/wolfram-language-notebook/blob/2fca803433842beb1dddc29084afd7bf279d5b53/src/extension/load-mathjax.ts#L16)是我导入mathjax的地方。
