### ISSUE TITLE
empty line is treated as input line

### ISSUE THREAD

**Issue by zhaoruiyang98** [njpipeorgan/wolfram-language-notebook#24]
**Description**
I find the treatment of empty line and comment in wolfram-language-notebook is different from that in mathematica notebook.

I attached the example.
![mma](https://user-images.githubusercontent.com/43402887/159153488-af43b870-5612-4d41-b578-8a87c907de62.png)
![wlnb](https://user-images.githubusercontent.com/43402887/159153513-c02d8672-82b9-43d5-83b6-8b2c6fd8c686.png)

I guess this issue is related to `\[NewLine]` and wolframscript. It may not be a bug, but sometimes I find it inconvenient when I want to reuse the output via `Out[n]`.

**Environment:**
 - Operating system: Windows 10
 - Mathematica/Engine: Mathematica 12.3.1/Wolfram Engine 12.3.1
 - VS Code: 1.65.2
 - Version: 0.0.9

**Comment by njpipeorgan** [comment]
The issue has been resolved in [8c66289](https://github.com/njpipeorgan/wolfram-language-notebook/commit/8c6628978561389ca25eba2c4a334d3b07d6ffe9).

**Comment by zhaoruiyang98** [comment]
Thank you very much for the quick fix! It helps me a lot : )
