### ISSUE TITLE
The kernel has stopped due to the following error: The first packet is not a InputNamePacket; packet=$Failed

### ISSUE THREAD

**Issue by giovannigravili** [njpipeorgan/wolfram-language-notebook#29]
When trying to run the notebook it says "The kernel has stopped due to the following error: The first packet is not a InputNamePacket; packet=$Failed". How should I fix this?

 - Operating system: MacOS
 - Mathematica/Engine: 13.0
 - VS Code: 1.68

It's a fresh install of everything.

**Comment by Nemo1166** [comment]
I have similar problem with you, and I haven't found a solution yet.

- OS: Windows 11
- Wolfram Engine:  13.0.1
- VS Code: 1.68

**Comment by njpipeorgan** [comment]
Thanks for your feedback. It is caused by a bug in the extension. As a workaround, try restart VS Code or reload the VS Code window after changing the kernel configuration.

**Comment by Nemo1166** [comment]
> Thanks for your feedback. It is caused by a bug in the extension. As a workaround, try restart VS Code or reload the VS Code window after changing the kernel configuration.

I tried your solution and now a new error appears: The kernel has stopped due to the following error: Failed to create a ZeroMQ local server on port 55340.

**Comment by giovannigravili** [comment]
I managed to get it to work by simply restarting the computer. There were so many kernels open in the background, check with Activity Monitor for "wolfram" processes active.

**Comment by ernestopalacios** [comment]
Hello everyone, this seems to be an intermittent problem, what works for me is:

When I first start VSCode I get the error described above, what I do is:

View Terminal -> Select: Output -> Select: Wolfram Language Notebook.

Run a very Simple Line: `In 1>:  4 + 1`

Then, in my case, VSCode asks me to choose an engine, I choose the first one on the list, it does is thing, and it works.

So far this is the most successful procedure I got.
