### ISSUE TITLE
重启内核失败

### ISSUE THREAD

**Issue by xiajunwen1007** [njpipeorgan/wolfram-language-notebook#3]
[Thu, 02 Dec 2021 03:27:49 GMT] kernelIsRemote = false, kernelPort = 65434
[Thu, 02 Dec 2021 03:27:49 GMT] launchCommand = wolframscript
[Thu, 02 Dec 2021 03:27:49 GMT] launchArguments = -code,ToExpression["zmqPort=65434;"<>Uncompress["1:eJzFXP9T20iyv//i/aoMFM9QsmOS2rv3APlMCHnhli8BO5eqVXQgrAnWIUteSQ54jfO3X/d8kWZGkvElu/eoSrA1Mz093T3dn+4Z8eI2uRr8189/+lNrx9rb++CP7v07urdn7Wx/7u6+wn+sYUBHe
[Thu, 02 Dec 2021 03:27:50 GMT] Received the following data from kernel (stderr):
[Thu, 02 Dec 2021 03:27:50 GMT] 
Your Wolfram Engine installation is not activated or is experiencing a license-related problem.

Please run wolframscript with the -activate option, and then try
 your original wolframscript command again.

[Thu, 02 Dec 2021 03:27:50 GMT] Killing kernel process, pid = 1014
[Thu, 02 Dec 2021 03:27:50 GMT] Process exited with code 255 and signal null.

用内置命令重启内核后会直接失败并且出现授权问题，直接在命令行输入wolframscript会出现免费的liscense只能两个设备使用的问题，从而激活不了

The Wolfram Engine could not be activated using your Wolfram ID.

This may have occurred because WolframScript has already activated a different
 installation of the Wolfram Engine using your account's limited
 free activation keys. Only two keys are generated
 when you create a free Wolfram Engine license using
 https://www.wolfram.com/engine/free-license/.

For additional Wolfram Engine keys, contact Wolfram Research at
 https://www.wolfram.com/contact-us/.

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by xiajunwen1007** [comment]
好像只要关闭vscode再开启vscode就会出现这个问题，感觉是因为vscode退出后连接没有中断导致的

**Comment by xiajunwen1007** [comment]
在终端中发现确实多出了好几个kernel，如果把这些kernel全关掉就正常了

**Comment by xiajunwen1007** [comment]
是不是添加一条命令先检查是否存在kernel，如果存在就不添加新的kernel。重启kernel的命令感觉像是直接新建一个kernel而不是先关闭再添加一个。关闭kernel的这个命令是可以使用的，先使用关闭kernel再启动一个kernel这两个操作和在一起是没问题的

**Comment by njpipeorgan** [comment]
你可以试一下安装[这个版本](https://raw.githubusercontent.com/njpipeorgan/wolfram-language-notebook/main/vsix/wolfram-language-notebook-0.0.5.vsix)，看看内核重启的问题有没有解决

**Comment by xiajunwen1007** [comment]
解决了，感谢
