### ISSUE TITLE
How do I enable the Wolfram Language extension in VS Code?

### ISSUE THREAD

**Issue by DougAtClir** [njpipeorgan/wolfram-language-notebook#33]
When I check the runtime status of the newly installed Wolfram Language extension (1.7.0) it says "Not yet activated".

None of the commands associated with this extension appear in the pallette.  

How do I activate the Wolfram Language extension.

**Comment by The3DWizard** [comment]
This is the Wolfram Language Notebook extension, not the Wolfram Language extension. You need to ask you question there.
