### ISSUE TITLE
The universal build VSCode cannot launch the extension

### ISSUE THREAD

**Issue by xiajunwen1007** [njpipeorgan/wolfram-language-notebook#4]
[2021-12-01 01:01:53.024] [exthost] [error] Activating extension njpipeorgan.wolfram-language-notebook failed due to an error:
[2021-12-01 01:01:53.024] [exthost] [error] Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=89 uv=1 armv=8 libc=glibc node=14.16.0 electron=13.5.2
loaded from: /Users/xiajunwen/.vscode/extensions/njpipeorgan.wolfram-language-notebook-0.0.2/node_modules/zeromq

I think this could be an issue from VSCode itself, cause the intel build is OK. Maybe this error should be posted to VSCode team as well.

**Comment by njpipeorgan** [comment]
The reason is likely that the [zeromq](https://www.npmjs.com/package/zeromq) package does not come with prebuilt binary for m1 macbook (darwin + arm64). It is noted in zeromq issue [#477](https://github.com/zeromq/zeromq.js/issues/477)

**Comment by xiajunwen1007** [comment]
Yes, you are right

**Comment by xiajunwen1007** [comment]
I’m sorry to bring this up again. I notice that the native arm64 build of zeromq is impossible in the near future, so I'm wondering is it possible to force x86 version of zeromq. Since the x86 version of zeromq works quite well on m1 machine.
