### ISSUE TITLE
Not able to launch the kernel

### ISSUE THREAD

**Issue by mtwtf-ss** [njpipeorgan/wolfram-language-notebook#49]
**Describe the bug**
Can't connect to the kernel:
Error message: "The kernel has stopped due to the following error: The first packet is not a InputNamePacket; packet=$Failed

**Expected behavior**
No error message.

**Screenshots**
![vscode error](https://github.com/njpipeorgan/wolfram-language-notebook/assets/138087900/01e02b4d-3fa9-4246-ab5c-2180a289fc1c)
![image](https://github.com/njpipeorgan/wolfram-language-notebook/assets/138087900/c2bfab1d-8600-45f2-94f8-400fdfd09160)

**Environment (please complete the following information):**
 - Operating system: Windows 11
 - Mathematica/Engine: 13.1
 - VS Code: 1.79.2
 - Version: 

**Additional context**
I was able to run the kernel right after installation, but after then I was not able to re-launch it.

**Comment by bzjan** [comment]
Do you have the official Wolfram language extension installed? If you have it, disable it. It already calls a wolfram kernel on startup interfering with this extension.

**Comment by mtwtf-ss** [comment]
Ah, I see. Thank you for the suggestions! It worked.
