### ISSUE TITLE
"Could not initialize webview" error

### ISSUE THREAD

**Issue by SjoerdSmitWolfram** [njpipeorgan/wolfram-language-notebook#52]
I followed the steps on the VSCode homepage for the plugin. When I try to use the `Create New Wolfram Language Notebook` command, I get the following error:

![image](https://github.com/njpipeorgan/wolfram-language-notebook/assets/77680787/c2044ef7-e658-45f0-b0e5-8e801941173c)

 - Operating system: Win 10
 - Mathematica/Engine: [13.3.1] (Wolfram Language 13.3.1 Engine for Microsoft Windows (64-bit))
 - VS Code:
![image](https://github.com/njpipeorgan/wolfram-language-notebook/assets/77680787/e99de592-d754-411c-b609-23f49bede828)
 - Version: 0.1.1

**Comment by SjoerdSmitWolfram** [comment]
Oh, the problem seems to have gone away now.

One recommendation: the instructions on the marketplace start with 

> To create a new Wolfram Language notebook, execute Create New Wolfram Language Notebook in the Command Palette, or create a new file with .wlnb extension.

> Execute Manage Kernels command and choose Use wolframscript to add wolframscript to the kernel configuration and connect to it. The status of the kernel will be shown in the status bar.

These two instructions should be reversed: the user should first set up the kernel and only THEN attempt to create a notebook.

**Comment by wuyudi** [comment]
there is another way: create a empty txt, rename to wlnb, open it.

vscode will automatically recognize it.
