### ISSUE TITLE
Unable to display an image

### ISSUE THREAD

**Issue by Florianismeandonlyme** [njpipeorgan/wolfram-language-notebook#7]
**As the title suggests**
Everything is okay include display an equation, solve a differential equation. 
THE IMAGE JUST DONT SHOWN UP, even if there's no an error report

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/58820847/146677664-22b94dfd-08a8-4910-bb49-01d48d875fa9.png)

**Environment (please complete the following information):**
Here is my configuration settings
![image](https://user-images.githubusercontent.com/58820847/146677679-f328112c-8c36-4999-90b8-2f999e220e09.png)

**Comment by njpipeorgan** [comment]
Which Wolfram Engine version, OS, VS Code version, and extension version are you using?

**Comment by Florianismeandonlyme** [comment]
Both my Mathematica and Wolfram Engine version is 12.3, the extension version is v0.06

P.S: Sometimes when the wolfram engine would notice me to Launch a mathlink program
![image](https://user-images.githubusercontent.com/58820847/147378059-eeabd9e6-0edb-4941-a31b-f56f4c116b9c.png)
and when  I run the codes again, there would be a 'rending failed' error:
![image](https://user-images.githubusercontent.com/58820847/147378073-d3070c7e-6bd5-47d7-86e0-f6c6badf77e3.png)




> Which Wolfram Engine version, OS, VS Code version, and extension version are you using?

**Comment by njpipeorgan** [comment]
I was not able reproduce this problem with Engine 12.3. I suspect that the subkernel was not launched successfully. 

You can try opening the output window (Ctrl+Shift+U) and select the Wolfram Language Notebook tab while connecting to the kernel, and see what the output is.

**Comment by lyyc199586** [comment]
Same question here, I can generate 2D plots, but fail with 3D ones (generate a blank figure)

```
ContourPlot3D[
 x^3 + y^2 - z^2 == 0, {x, -2, 2}, {y, -2, 2}, {z, -2, 2}]
```
![image](https://user-images.githubusercontent.com/20653957/150618547-6d3bfbf1-4910-4c7e-82b8-5ca6424455d7.png)

```
Plot[Sin[x],{x,-1,1}]
```
![image](https://user-images.githubusercontent.com/20653957/150618570-74fa07ac-c610-4b83-a89f-76019e011f57.png)

**Comment by lyyc199586** [comment]
when changes to plain text, the output looks fine:
![image](https://user-images.githubusercontent.com/20653957/150619085-d59913ff-09e7-434c-ad8b-a611cfc22769.png)

so I doubt this is something wrong with the notebook render  for 3D plots.

The info from output tab:
```
[Sat, 22 Jan 2022 01:17:57 GMT] kernelIsRemote = false, kernelPort = 58232
[Sat, 22 Jan 2022 01:17:57 GMT] kernelInitPath = /home/yang/.vscode-server/extensions/njpipeorgan.wolfram-language-notebook-0.0.8/resources/init-compressed.txt
[Sat, 22 Jan 2022 01:17:57 GMT] kernelRenderInitPath = /home/yang/.vscode-server/extensions/njpipeorgan.wolfram-language-notebook-0.0.8/resources/render-html.wl
[Sat, 22 Jan 2022 01:17:57 GMT] launchCommand = wolframscript
[Sat, 22 Jan 2022 01:17:57 GMT] launchArguments = -code,ToExpression["zmqPort=58232;"<>Uncompress["1:eJy9PA1X47ay96d4BYcTuApLdl/73gGSF5aPu9wCy5Jse0+9LphES1wcO7WdBRrSH/t+yZvRhy3Jdgh0W1qWxJJGo5nRfGnkV9fxRe//fvrHPxobzvb2uT+49W/Y9razsf55q/UGf3lDjw2yII7yh
[Sat, 22 Jan 2022 01:17:59 GMT] Received the following data from kernel:
[Sat, 22 Jan 2022 01:17:59 GMT] <INITIALIZATION STARTS>
[Sat, 22 Jan 2022 01:18:00 GMT] Received the following data from kernel:
[Sat, 22 Jan 2022 01:18:00 GMT] $CommandLine={/usr/local/Wolfram/WolframEngine/13.0/SystemFiles/Kernel/Binaries/Linux-x86-64/WolframKernel, -runfirst, Unprotect[$EvaluationEnvironment];$EvaluationEnvironment="Script";Protect[$EvaluationEnvironme
[Sat, 22 Jan 2022 01:18:00 GMT] Received the following data from kernel:
[Sat, 22 Jan 2022 01:18:00 GMT] $ScriptCommandLine={wolframscript, -code, ToExpression["zmqPort=58232;"<>Uncompress["1:eJy9PA1X47ay96d4BYcTuApLdl/73gGSF5aPu9wCy5Jse0+9LphES1wcO7WdBRrSH/t+yZvRhy3Jdgh0W1qWxJJGo5nRfGnkV9fxRe//fvrHPxobzvb2uT+49W/Y9razsf55
[Sat, 22 Jan 2022 01:18:00 GMT] Received the following data from kernel:
[Sat, 22 Jan 2022 01:18:00 GMT] Using the following command to launch the subkernel process:
[Sat, 22 Jan 2022 01:18:00 GMT] Received the following data from kernel:
[Sat, 22 Jan 2022 01:18:00 GMT] /usr/local/Wolfram/WolframEngine/13.0/SystemFiles/Kernel/Binaries/Linux-x86-64/WolframKernel -noicon -wstp -linkprotocol SharedMemory -linkmode connect -linkname 5128a689-2f8b-4450-8a4d-af543853cb37
[Sat, 22 Jan 2022 01:18:02 GMT] Received the following data from kernel:
[Sat, 22 Jan 2022 01:18:02 GMT] Subkernel launched; $preemptive=LinkObject[9f3044fa-1bec-4d5d-91a5-8e290dd53b81, 193, 3], $processID=252
[Sat, 22 Jan 2022 01:18:02 GMT] Received the following data from kernel:
[Sat, 22 Jan 2022 01:18:02 GMT] [address tcp://127.0.0.1:58232]

[Sat, 22 Jan 2022 01:18:02 GMT] Received the following data from kernel:
[Sat, 22 Jan 2022 01:18:02 GMT] <INITIALIZATION ENDS>
[Sat, 22 Jan 2022 01:18:02 GMT] Received the following test message from kernel:
[Sat, 22 Jan 2022 01:18:02 GMT] {"type":"test","text":"100405031","version":"13.0.0 for Linux x86 (64-bit) (December 10, 2021)"}
```
@njpipeorgan

**Comment by njpipeorgan** [comment]
Thanks for the feedback. I cannot reproduce this issue on Windows/Linux with Mathematica/Engine 13.0. As it was a blank image and Plot did work, I suspect that it may be a kernel-related problem. How about converting the graphics to an image manually, like `Rasterize[ContourPlot3D[x^3 + y^2 - z^2 == 0, {x, -2, 2}, {y, -2, 2}, {z, -2, 2}]]` ?

Maybe you can try disabling all other extensions or reinstalling the kernel.

**Comment by lyyc199586** [comment]
`Rasterize` didn't help... 

I am using wolframscirpt:
```
yang@SP8:/mnt/c/Users/liuya$ wolframscript
Wolfram Language 13.0.0 Engine for Linux x86 (64-bit)
Copyright 1988-2021 Wolfram Research, Inc.

In[1]:= $Version                                                                                                        
Out[1]= 13.0.0 for Linux x86 (64-bit) (December 10, 2021)

In[2]:=   
```

**Comment by lyyc199586** [comment]
disabling all other exts doesn't help either

**Comment by njpipeorgan** [comment]
> `Rasterize` didn't help...
> 
> I am using wolframscirpt:
> 
> ```
> yang@SP8:/mnt/c/Users/liuya$ wolframscript
> Wolfram Language 13.0.0 Engine for Linux x86 (64-bit)
> Copyright 1988-2021 Wolfram Research, Inc.
> 
> In[1]:= $Version                                                                                                        
> Out[1]= 13.0.0 for Linux x86 (64-bit) (December 10, 2021)
> 
> In[2]:=   
> ```

Are you using the kernel over WSL?

**Comment by lyyc199586** [comment]
> 

Yes, WSL2 (ubuntu)

**Comment by njpipeorgan** [comment]
As far as I know, the kernel relies on X windows system to render some graphics, which can go wrong in WSL.

**Comment by lyyc199586** [comment]
This is a little bit frastrating..

There is a similar work on using Jupyter notebook as an frontend for mma in browser, (WolframLanguageForJupyter)[https://github.com/WolframResearch/WolframLanguageForJupyter]. But this didn't work for vscode.

Anyway, I think your extension is the by far the best solution to use mma notebook in vscode. bravo!

What is your platform?

**Comment by njpipeorgan** [comment]
VSCode has native support for Jupyter, so I assume WolframLanguageForJupyter as a Jupyter kernel can work in VSCode. But I'm not sure whether that will solve this problem. 

Thanks.

I've been testing the extension on Windows, Ubuntu, and MacOS.

**Comment by lyyc199586** [comment]
WolframLanguageForJupyter didnt work in vscode, I have tried it when find that repo... and there is an issue about that [issue](https://github.com/WolframResearch/WolframLanguageForJupyter/issues/97).

Only 3D plots don't work, that's very strange... 

![image](https://user-images.githubusercontent.com/20653957/150621152-58c70ac4-ea4a-4abd-bb93-986d510b4218.png)

**Comment by njpipeorgan** [comment]
Thanks for the info. You can also testing rasterizing 3D graphics in the kernel in WSL terminal directly, e.g.
```
img=ImageData[Rasterize[ContourPlot3D[x^3 + y^2 - z^2 == 0, {x, -2, 2}, {y, -2, 2}, {z, -2, 2}]]];
Dimensions[img]
Mean[Mean[img]]
```
and see if it is normal.

**Comment by lyyc199586** [comment]
that looks fine
```bash
yang@SP8:/mnt/c/Users/liuya$ wolframscript
Wolfram Language 13.0.0 Engine for Linux x86 (64-bit)
Copyright 1988-2021 Wolfram Research, Inc.

In[1]:= img=ImageData[Rasterize[ContourPlot3D[x^3 + y^2 - z^2 == 0, {x, -2, 2}, {y, -2, 2}, {z, -2, 2}]]];

In[2]:= Dimensions[img]

Out[2]= {549, 481, 3}

In[3]:= Mean[Mean[img]]

Out[3]= {1., 1., 1.}

In[4]:=  
```

**Comment by njpipeorgan** [comment]
It actually did not look fine. Note that the average of the image was `{1.,1.,1.}`, which means it was a blank image.

**Comment by lyyc199586** [comment]
yea... that's weird, let my check it in a jupyter noteboook in browser

**Comment by lyyc199586** [comment]
I think that bug only occur on WoframEngine 13.0, because I remember that I could generate 3d plots when I was using 12.3, (or they removed this feature in 13.)

🤣

**Comment by lyyc199586** [comment]
Finally I'm sure this is a bug only on WSL, I tried it on windows and it works fine.

**Comment by njpipeorgan** [comment]
Thanks for the information.
