### ISSUE TITLE
could not connect due to something wrong with InputNamePacket

### ISSUE THREAD

**Issue by hg1qR0qPN** [njpipeorgan/wolfram-language-notebook#9]
Fail to connect to Wolfram Engine. It pops the following error:
![Screenshot_20220107_134239](https://user-images.githubusercontent.com/61173671/148497739-1d977175-278b-4cae-aa48-7c85a515ae2b.png)

When clicked "Test in terminal", it looks fine:
![Screenshot_20220107_133105](https://user-images.githubusercontent.com/61173671/148497606-71a06f9c-b233-4b57-a630-135af5dfcd4a.png)

I have tried to change `"command"` to the full path to `wolframscript` but it doesn't work.

my environment:
 - Operating system: Ubuntu 20.04.2 x86_64
 - Mathematica/Engine: Wolfram Engine 13.0.0, Wolfram Script 1.7.0
 - VS Code: 1.63.2
 - Version: 0.0.7

VS Code settings:
```
    "wolframLanguageNotebook.kernel.connectionTimeout": 3000,
    "wolframLanguageNotebook.kernel.configurations": {
        "default": {
            "type": "local",
            "command": "wolframscript",
            "ports": "6537"
        }
    },
    "wolframLanguageNotebook.kernel.connectOnOpeningNotebook": "default"
```

**Comment by njpipeorgan** [comment]
I can reproduce this error when I have another wolframscript running. (Wolfram Engine have the limitation that only one wolframscript can be run at a time.) You can try killing all wolframscript/WolfranKernel processes before connecting to a kernel. If it does not work, you can open the output panel with Ctrl+Shift+U and select the "Wolfram Language Notebook" tab, where extra information will be shown when you connect to a kernel.

**Comment by hg1qR0qPN** [comment]
It works after killing all WolframKernel processes. Thanks a lot!!

**Comment by bzjan** [comment]
An alternative cause for this error is when you have the official Wolfram Language extension running. It automatically runs a wolfram kernel. So the solution is to disable the official Wolfram Language extension.
